AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - db/schema.rb
    - db/restore_schema.rb
    - db/migrate/*
    - script/**/*

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/routes/*
    - spec/**/*
