AllCops:
  TargetRubyVersion: 2.1
  Exclude:
    - db/schema.rb
    - db/restore_schema.rb
    - db/migrate/*
    - script/**/*

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/routes/*
    - spec/**/*

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SingleLineBlockParams:
  Enabled: false
